version: '3.9'

volumes:
  datastore:

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
      target: local
    container_name: ${CONTAINER_NAME}_nginx
    volumes:
      - ./public:/var/www/html/public:ro
    ports:
      - 80:80
    environment:
      PHP_HOST: php
    env_file: .env

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      target: development
    container_name: ${CONTAINER_NAME}_php
    env_file: .env
    volumes:
      - type: bind
        source: .
        target: /var/www/html

  mariadb:
    build:
      context: .
      dockerfile: ./.docker/mariadb/Dockerfile
    container_name: ${CONTAINER_NAME}_mariadb
    env_file: .env
    ports:
      - 3306
    volumes:
      - datastore:/var/lib/mysql

  pma:
    build:
      context: .
      dockerfile: ./.docker/pma/Dockerfile
      target: builder
    container_name: ${CONTAINER_NAME}_pma
    depends_on:
      - ${CONTAINER_NAME}_mariadb
    env_file: .env
    ports:
      - 8080:80

  mail:
    image: mailhog/mailhog
    container_name: ${CONTAINER_NAME}_mail
    ports:
      - 8025:8025
    env_file: .env

